version: '3'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=blog

  php:
    build: php
    ports:
      - 9000:9000
    links:
      - db:mysql
    volumes:
      - ./api:/usr/src/app

  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/public:/usr/src/app


