swagger_ui:
  path: /api/docs
  controller: api_platform.swagger.action.ui

index:
  path: /
  controller: App\Controller\Home\HomeAction

register:
  path: /api/register
  controller: App\Controller\Authentication\LoginAction
  methods: [GET|POST]

api:
  path: /api/v1
  controller: App\Controller\AuthController::api

api_login:
  path: /api/login
  controller: App\Controller\Authentication\LoginAction
  methods: [GET]

api_login_check:
  path: /api/login_check
  methods: [POST]

admin:
  path: /admin
  methods: [GET]