swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui

index:
  path: /
  controller: App\Controller\HomeController::index

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: [GET|POST]

admin_login:
  path: /admin/login
  controller: App\Controller\SecurityController::login
  methods: [GET|POST]

admin_logout:
  path: /admin/logout
  controller: App\Controller\SecurityController:logout
  methods: [GET]

api:
  path: /api/v1
  controller: App\Controller\AuthController::api

api_login:
  path: /api/login
  controller: App\Controller\AuthController::login
  methods: [GET]

api_login_check:
  path: /api/login_check
  methods: [POST]

admin:
  path: /admin
  methods: [GET]