name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: shivammathur/setup-php@v2
      with:
          php-version: '7.4'
          coverage: none
          tools: composer:v1, psalm

    - name: Install dependencies
      working-directory: ./api
      run: composer update --prefer-dist --no-progress --ansi

    - name: Psalm
      working-directory: ./api
      run: psalm --output-format=github --shepherd

    - name: Setup and run tests
      working-directory: ./api
      run: |
        php vendor/bin/simple-phpunit